### PR TITLE
add debian package files

### PR DESCRIPTION
**Pull request by yocalebo**
Hi @aravindavk , as I said in the past I work with iXsystems and I use this library heavily. Internally, I was packaging this as a debian apt package because pip installations were not an option. However, one of the problems I ran into is that this package had a name collision with another python module that came installed with the `glusterfs-server` package.

Anyways, now that you have renamed it from `gluster` to `glustercli` this is no longer a problem 😄 

I've added the debian sources that would be needed to build this as an debian apt package.

### CODE REVIEW

**Comment by aravindavk** [comment]
This is great. I will review this PR by tomorrow. Thanks for sending it.

**Comment by yocalebo** [comment]
> This is great. I will review this PR by tomorrow. Thanks for sending it.

Thanks for reviewing. Please let me know if I need to make any changes as it will be no problem 👍

**Comment by aravindavk** [comment]
How to test this Patch? Please let me know the steps, I will run it once.

**Comment by yocalebo** [comment]
@aravindavk You'll need a debian system (obviously) but here are the rough steps to test this.

1. git checkout this branch
2. `cd` into the branch you checked out
3. run `git archive --format=tar.gz --worktree-attributes -o ../glustercli_0.7.orig.tar.gz HEAD`
4. run `dpkg-buildpackage -sa -uc -us`

Once you have done this, it should build this and in the directory above your local branch. So `cd ..` and you should have a file that looks like this `python3-glustercli_0.7-1_all.deb`.

Once you have the deb file, you can install it by doing `dpkg -i python3-glustercli_0.7-1_all.deb`. Then you can open up a python IDE and import the libraries and test to make sure they work.

**Comment by yocalebo** [comment]
Hi @aravindavk , I'm just checking in to see if you were able to test this on your side? We're currently using these exact files to build a debian apt package and installing it in our distribution without issues.

**Review by aravindavk — APPROVED** [review]

**Pull request merged**
